---
title: "BIOS512_HW3_WILLIAMS"
output: html_document
---

Question 1 


Question 2

git clone https://github.com/BellaReaWilliams/BIOS512_Williams.git 
cd BIOS512_Williams
git add README.md
git commit -m ""added notes file""initial commit"
git push origin main

Question 3

SSH key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIL0LqOOxhPpyW9wtvvZaqLiQkAMZs8CX0iCiMrJEdvdr breaw@unc.edu 

Question 4

e) Rename HW2.md to HW2_editedtitle.md
f)

git status

On branch main
Your branch is up to date with 'origin/main'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	HW2/HW2.md

nothing added to commit but untracked files present (use "git add" to track)
bellawilliams@Bellas-MacBook-Air-6 BIOS512_Williams % 

g) git log --oneline

934bdcd (HEAD -> main, origin/main, origin/HEAD) Updated HW2.md with new content for step G
660426a Updated title to HW2.md
bac2cdc Rename HW2.md to HW2_editedtitle.md
0dc13ce Added HW2 directory with HW2.md
708f4f2 Add files via upload
5b8d7aa Delete BIOS512_HW2-1 (1).ipynb
aa13983 Add files via upload
0686b89 install.R
01dee82 apt.txt
b2ea135 install.R
a2ec7e6 Update README.md
71291c4 Update README.md
b712891 Update README.md
af73a07 Update README.md
566d61d Update README.md
c89dcad add cars.csv
cd73b1e Add files via upload
381683c add install.R
581d48a add runtime.txt
09dfe19 initial commit
bellawilliams@Bellas-MacBook-Air-6 BIOS512_Williams % 

h)

git help log

--since in regards to the git log filters commits to show only those that are more recent than a specified date. 

This is the documentation:

--since=<date1> limits to commits newer than <date1>, and using it with
       --grep=<pattern> further limits to commits         whose log message has a line
       that matches <pattern>), unless otherwise          noted.
--since=<date>, --after=<date>
           Show commits more recent than <date>.

--since-as-filter=<date>
           Show all commits more recent than                  <date>. This visits all commits
           in the range, rather than stopping at              the first commit which is
           older than <date>.
           
library(tidyverse)
if (!dir.exists("intermediate")) dir.create("intermediate", recursive = TRUE)
if (!exists("mdpre")) mdpre <- function(x) { print(x) }
if (!exists("ggmd"))  ggmd  <- function(p) { print(p) }

Question 5

Question 6

Question 7

Question 8

Question 9

Question 10

Question 11

Question 12
